package com.github.bigdata.sql.parser

/**
 * Created by libinsong on 2017/3/6.
 */

enum class SQLOperationType {
    CREATE_DATABASE,
    DROP_DATABASE,
    DESC_DATABASE,

    CREATE_TABLE,
    CREATE_TABLE_AS_SELECT,
    CREATE_TABLE_AS_LIKE,
    DROP_TABLE,
    TRUNCATE_TABLE,
    RENAME_TABLE, //mysql
    READ_TABLE,
    MERGE_TABLE,
    REFRESH_TABLE,
    LOAD_TABLE,
    ANALYZE_TABLE,

    ALTER_TABLE_RENAME,
    ALTER_TABLE_ADD_COLS,
    ALTER_TABLE_ADD_COL,
    ALTER_TABLE_DROP_COL,
    ALTER_TABLE_RENAME_COL,
    ALTER_TABLE_CHANGE_COL,
    ALTER_TABLE_MODIFY_COL, //mysql
    ALTER_TABLE_DROP_PARTS,
    ALTER_TABLE_ADD_PARTS,
    ALTER_TABLE_RENAME_PART,
    ALTER_TABLE_PROPERTIES,
    DESC_TABLE,
    MSCK_TABLE,
    //mysql
    ALTER_TABLE,
    //ALTERTABLE_DROPPROPERTIES,
    ALTER_TABLE_TOUCH,

    //DML
    QUERY,
    SELECT,
    DELETE,
    UPDATE,
    INSERT_VALUES,
    INSERT_SELECT,
    MULTI_INSERT,

    CREATE_VIEW,
    DROP_VIEW,
    ALTER_VIEW_QUERY,
    ALTER_VIEW_RENAME,
    ALTER_VIEW_PROPERTIES,

    CREATE_FUNCTION,
    DROP_FUNCTION,

    SHOW, //mysql 命令
    SHOW_COLUMNS,
    SHOW_PARTITIONS,
    SHOW_TABLES,
    SHOW_TABLE,
    SHOW_TABLE_PROPERTIES,
    SHOW_CREATE_TABLE,

    SHOW_FUNCTIONS,
    DESC_FUNCTION,

    LIST_JARS,
    DELETE_JAR,

    KILL,
    STATUS,

    CACHE,
    UNCACHE,
    CLEAR_CACHE,

    EXPLAIN,
    SET,
    JOB,

    UNKOWN;
}