WITH TMP_BS_FOREX_ORDER AS (
    SELECT ORDER_ID,
           ATTR,
           SOURCE,
           DATA_FLAG
    FROM (
             SELECT ID AS ORDER_ID, ATTR, SOURCE, 'TBNZ' AS DATA_FLAG
             FROM ODS.ALPHA_ONLINE_ORDERS A
             WHERE SEC_TYPE = 'FOREX'
             UNION ALL
             SELECT ID AS ORDER_ID, ATTR, SOURCE, 'TBSG' AS DATA_FLAG
             FROM ODS.SG_ALPHA_ONLINE_ORDERS A
             WHERE SEC_TYPE = 'FOREX'
             UNION ALL
             SELECT ID AS ORDER_ID, ATTR, SOURCE, 'TBAU' AS DATA_FLAG
             FROM ODS.AU_ALPHA_ONLINE_ORDERS A
             WHERE SEC_TYPE = 'FOREX'
             UNION ALL
             SELECT ID AS ORDER_ID, ATTR, SOURCE, 'TFNZ' AS DATA_FLAG
             FROM ODS.TFNZ_ALPHA_ONLINE_ORDERS A
             WHERE SEC_TYPE = 'FOREX'
         ) A
    GROUP BY ORDER_ID, ATTR, SOURCE, DATA_FLAG
)
, TMP_BS_FOREX_COUPON_ORDER AS (
SELECT ORDER_ID,
       DATA_FLAG
FROM (
         SELECT ORDER_ID, 'TBNZ' AS DATA_FLAG
         FROM ODS.ALPHA_ONLINE_COUPON_ORDERS A
                  INNER JOIN ODS.ALPHA_ONLINE_ORDERS B ON A.ORDER_ID = B.ID
         WHERE B.SEC_TYPE = 'FOREX'

         UNION ALL

         SELECT ORDER_ID, 'TBSG' AS DATA_FLAG
         FROM ODS.SG_ALPHA_ONLINE_COUPON_ORDERS A
                  INNER JOIN ODS.SG_ALPHA_ONLINE_ORDERS B ON A.ORDER_ID = B.ID
         WHERE B.SEC_TYPE = 'FOREX'

         UNION ALL

         SELECT ORDER_ID, 'TBAU' AS DATA_FLAG
         FROM ODS.AU_ALPHA_ONLINE_COUPON_ORDERS A
                  INNER JOIN ODS.AU_ALPHA_ONLINE_ORDERS B ON A.ORDER_ID = B.ID
         WHERE B.SEC_TYPE = 'FOREX'

         UNION ALL

         SELECT ORDER_ID, 'TFNZ' AS DATA_FLAG
         FROM ODS.TFNZ_ALPHA_ONLINE_COUPON_ORDERS A
                  INNER JOIN ODS.TFNZ_ALPHA_ONLINE_ORDERS B ON A.ORDER_ID = B.ID
         WHERE B.SEC_TYPE = 'FOREX'
     ) A
GROUP BY ORDER_ID, DATA_FLAG
)
, RESULT AS (
        SELECT
            A.PID
             , A.EXECUTING_BROKER
             , A.CLEARING_BROKER
             , A.REF_TYPE AS BEHAVIOR_TYPE
             , A.TRADE_DATE AS BEHAVIOR_DATE    -- 当地时间
             , A.TRANSACT_TIME AS BEHAVIOR_TIME -- 北京时间
             , A.TRADE_ID
             , CAST (A.ORDER_ID AS STRING) AS ORDER_ID
             , B.SOURCE AS TRADE_ORDER_SOURCE
             , A.IS_AUTO_EXCHANGE
             , CASE WHEN CAST (B.ATTR AS BIGINT) & CAST (POW(2, 18) AS BIGINT)= CAST (POW(2, 18) AS BIGINT) THEN 1 ELSE 0 END AS IS_TRADE_GREY_MARKET
       , CASE WHEN C.ORDER_ID IS NOT NULL THEN 1 ELSE 0 END AS IS_COUPON_USED
            , CAST (A.ACCOUNT_ID AS STRING) AS ACCOUNT_ID
            , CAST (A.STOCK_ID AS STRING) AS STOCK_ID
            , A.`SYMBOL`
            , A.SEC_TYPE
            , A.MARKET
            , A.`EXCHANGE`
            , A.SIDE AS ACTION
            , A.CURRENCY
            , A.AVG_COST AS AVG_PRICE
            , A.DECIMAL_QTY AS QTY
            , A.MULTIPLIER
            , A.AMOUNT
            , A.FOREX_INCOME AS COMMISSION
            , A.FOREX_COST AS EXPENSE
            , A.FOREX_INCOME-NVL(A.FOREX_COST, 0) AS NET
            , A.CURRENCY AS COMMISSION_CURRENCY
            , A.DATA_FLAG
            , A.CREATED_AT
            , A.UPDATED_AT
    FROM DWD.DWD_BS_FOREX_TRADE_DETAIL_A_D A
        LEFT JOIN TMP_BS_FOREX_ORDER B
    ON A.ORDER_ID=B.ORDER_ID AND A.DATA_FLAG=B.DATA_FLAG
        LEFT JOIN TMP_BS_FOREX_COUPON_ORDER C ON A.ORDER_ID= C.ORDER_ID AND A.DATA_FLAG= C.DATA_FLAG

    UNION ALL
    SELECT
        PID
         , 'IB' AS EXECUTING_BROKER
         , 'IB' AS CLEARING_BROKER
         , A.BEHAVIOR_TYPE
         , A.BEHAVIOR_DATE                                                                                                           -- 当地日期
         , CAST (FROM_UTC_TIMESTAMP(TO_UTC_TIMESTAMP(A.TRADE_TIME, 'AMERICA/NEW_YORK'), 'ASIA/SHANGHAI') AS STRING) AS BEHAVIOR_TIME -- 美东转北京地时间
         , A.TRADE_ID
         , A.ORDER_ID
         , A.TRADE_ORDER_SOURCE
         , 0 AS IS_AUTO_EXCHANGE
         , NULL AS IS_TRADE_GREY_MARKET
         , NULL AS IS_COUPON_USED
         , A.ACCOUNT AS ACCOUNT_ID
         , NULL AS STOCK_ID
         , A.`SYMBOL`
         , A.SEC_TYPE
         , A.MARKET
         , A.`EXCHANGE`
         , A.ACTION
         , A.CURRENCY
         , A.AVG_PRICE
         , A.QTY
         , A.MULTIPLIER
         , A.AMOUNT
         , A.COMMISSION
         , A.EXPENSE
         , A.NET
         , A.COMMISSION_CURRENCY
         , CASE WHEN LICENSE='TBNZ' THEN 'IB' WHEN LICENSE='US_IB' THEN 'US_IB' END AS DATA_FLAG
         , CAST (FROM_UTC_TIMESTAMP(TO_UTC_TIMESTAMP(A.TRADE_TIME, 'AMERICA/NEW_YORK'), 'ASIA/SHANGHAI') AS STRING) AS CREATED_AT
         , CAST (FROM_UTC_TIMESTAMP(TO_UTC_TIMESTAMP(A.TRADE_TIME, 'AMERICA/NEW_YORK'), 'ASIA/SHANGHAI') AS STRING) AS UPDATED_AT
    FROM DWD.DWD_IB_TRADE_DETAIL_A_D A
    WHERE A.SEC_TYPE='CASH'
)
INSERT OVERWRITE TABLE DWB.DWB_FOREX_TRADE_A_D
SELECT * FROM RESULT